name: Simple Next.js Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build static files
        run: npm run build
      - name: Check the build files
        run: ls -l .next/

      - name: Upload static files (artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          include-hidden-files: true
          path: .next/
